version: "3.3"
#name: 'grumpycat'

services:

  zookeeper:
    image: quay.io/strimzi/kafka:0.23.0-kafka-2.8.0
    command: [
      "sh", "-c",
      "bin/zookeeper-server-start.sh config/zookeeper.properties"
    ]
    ports:
      - "2181:2181"
    environment:
      LOG_DIR: /tmp/logs
    networks:
      - grumpycat-network

  kafka:
    image: quay.io/strimzi/kafka:0.23.0-kafka-2.8.0
    command: [
      "sh", "-c",
      "bin/kafka-server-start.sh config/server.properties --override listeners=$${KAFKA_LISTENERS} --override advertised.listeners=$${KAFKA_ADVERTISED_LISTENERS} --override zookeeper.connect=$${KAFKA_ZOOKEEPER_CONNECT}"
    ]
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      LOG_DIR: "/tmp/logs"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - grumpycat-network
  catsdb:
    image: docker.io/library/postgres:14.2
    volumes:
      - pg_data:/var/lib/postgresql
    restart: always
    environment:
      POSTGRES_USER: cat
      POSTGRES_PASSWORD: grumpy
      POSTGRES_DB: catdb
    networks:
      - grumpycat-network

  cat-server:
    depends_on: 
      - catsdb
      - zookeeper
      - kafka
    image: quay.io/wpernath/quarkus-grumpycat:v0.5.5
    ports:
      - "9001:8080"
    restart: always
    environment:
      DB_user: cat
      DB_password: grumpy
      DB_host: catsdb
      DB_dbname: catdb      
    networks:
      - grumpycat-network

  cat-client: 
    depends_on:
      - cat-server
    image: quay.io/wpernath/grumpycat-melonjs:v0.5.5
    ports:
      - "8086:8088"
    restart: always
    environment:
      APPLICATION_BASESERVERURL: "http://0.0.0.0:9001/"

    networks:
      - grumpycat-network

volumes:
  pg_data:

networks:
  grumpycat-network:
    name: grumpycat-whole-app-network